### ISSUE TITLE
InfinityLink兼容性问题

### ISSUE THREAD

**Issue by johnsilverhand** [BetterNCM/InfinityLink#10]
网易云可正常启动。但无法使用该插件。显示native plugin未加载。
![PX6(W5`{}F8WM5SP2I3DG8I](https://github.com/BetterNCM/InfinityLink/assets/90089156/af2c98ca-9856-4211-827d-fbe91e7f0330)

BetterNCM Installer版本为 1.0.5
适配BetterNCM 版本为：1.3.0-RC3
网易云版本：3.0.1
![1L_YB}`PA34PQT0N)EGSYJX](https://github.com/BetterNCM/InfinityLink/assets/90089156/956b04da-173f-4fec-b213-14f8cacbbe73)

C:\betterncm目录下的log.log文件内容显示为：
[InfLink] Plugin Native Plugin load Error: dll doesn't exists or is not adapted to this arch.

C:\betterncm\plugins_runtime\InfLink目录下的manifest.json文件中已有"ncm3-compatible": true,语句

C:\betterncm\plugins_runtime\InfLink目录下的easyrp.exe与start_easyrp.bat文件运行结果如下：

```
config file not found

shutting down...
```

**Comment by MicroCBer** [comment]
1.3.0-RC4 才支持 x64 的 Native Plugin 加载，而 InfLink 用到了此特性

等鸽子什么时候发个版就好
