### ISSUE TITLE
在beta3.0.0下信息不能获取的问题

### ISSUE THREAD

**Issue by Yu-xiaohei** [BetterNCM/InfinityLink#12]
在网易云音乐版本为beta3.0.0-201853下，使用1.3.0 RC4加载器时

该插件可以被加载运行，但使用DOM源时，信息不能被读取(消息通知栏中也没有在播放的状态)，不管是smtc还是rpc

手动运行rpc的easyrp.exe后，会强制下载目标为[这个](http://p1.music.126.net/jJOaqlez9x5VofjgB7B_Bw==/109951166195459631.jpg)的封面缓存，即使删掉SmallImage重新启动easyrp.exe，再次获取的依旧不变
![image](https://github.com/BetterNCM/InfinityLink/assets/110207616/a12ace28-cd81-49d8-9c98-f80d96c1d02c)

用麻匪的壁纸调用到的也是这个封面
![image](https://github.com/BetterNCM/InfinityLink/assets/110207616/42340c97-088f-46b5-b919-0a839c3bf165)
(自然也就没有歌曲信息什么的了)

---
> 突然发现日志里好像有dll不适用的报错
![image](https://github.com/BetterNCM/InfinityLink/assets/110207616/56555ec8-65d0-4a47-979b-0c31344bb141)

**Comment by Yu-xiaohei** [comment]
缓存图也都是重复的

**Comment by MicroCBer** [comment]
等3.0.0正式版再优化吧，现在每个版本都在改…

**Comment by yangnuozhen** [comment]
> 在网易云音乐版本为beta3.0.0-201853下，使用1.3.0 RC4加载器时
> 
> 该插件可以被加载运行，但使用DOM源时，信息不能被读取(消息通知栏中也没有在播放的状态)，不管是smtc还是rpc
> 
> 手动运行rpc的easyrp.exe后，会强制下载目标为[这个](http://p1.music.126.net/jJOaqlez9x5VofjgB7B_Bw==/109951166195459631.jpg)的封面缓存，即使删掉SmallImage重新启动easyrp.exe，再次获取的依旧不变 ![image](https://private-user-images.githubusercontent.com/110207616/262847803-a12ace28-cd81-49d8-9c98-f80d96c1d02c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDYzOTgsIm5iZiI6MTcxMDYwNjA5OCwicGF0aCI6Ii8xMTAyMDc2MTYvMjYyODQ3ODAzLWExMmFjZTI4LWNkODEtNDlkOC05Yzk4LWY4MGQ5NmMxZDAyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNjIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWNmMzA3YmZmZjdkNjQ0Y2FmYWViOGUxZGYyYmE1ZWFjOWM0MGZhYjFmNzVkZGY5OWRiMGMwZjMwOGJhMjQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FUF-_6SvSwdkVgaCB2ejoPpkwWAuUvt721fYb5PaF_Q)
> 
> 用麻匪的壁纸调用到的也是这个封面 ![image](https://private-user-images.githubusercontent.com/110207616/262847110-42340c97-088f-46b5-b919-0a839c3bf165.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDYzOTgsIm5iZiI6MTcxMDYwNjA5OCwicGF0aCI6Ii8xMTAyMDc2MTYvMjYyODQ3MTEwLTQyMzQwYzk3LTA4OGYtNDZiNS1iOTE5LTBhODM5YzNiZjE2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNjIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzcwOGFhOTk0NTUwODEzMjUyMTkxM2ZjZDk2NWNiZGYwYWNkNzE5YWU5MjNlNzE1MzYyNTcxNGY0NTg4OWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-V4LV0S0oG9tzys0e99sBbPhKTO8qvlNOxAXSKS-9i8) (自然也就没有歌曲信息什么的了)
> 
> > 突然发现日志里好像有dll不适用的报错
> > ![image](https://private-user-images.githubusercontent.com/110207616/262847551-56555ec8-65d0-4a47-979b-0c31344bb141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDYzOTgsIm5iZiI6MTcxMDYwNjA5OCwicGF0aCI6Ii8xMTAyMDc2MTYvMjYyODQ3NTUxLTU2NTU1ZWM4LTY1ZDAtNGE0Ny05NzliLTBjMzEzNDRiYjE0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNjIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjYwMmI0ZmMzZjJjYjVkNTllMTRmYmZhM2IzOTU5MjA0ZGQ0N2ZjNjg2Njk1YmVhZWQ3MGZiMDlmOWIzNGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7B6q_y68ZI25rAi_rS_YKsHjNKROgX365NWyMyrDjTo)

应该会有这个报错 等修吧
![image](https://github.com/BetterNCM/InfinityLink/assets/56541171/51af4cb3-0613-4601-93fc-af07f5230110)
