### ISSUE TITLE
部分拥有过短曲名的歌曲会导致easyrp自动退出

### ISSUE THREAD

**Issue by nyavana** [BetterNCM/InfinityLink#16]
不太清楚是 easyrp 还是 InfinityLink 的问题。
Windows 11, 网易云版本 2.10.12，InfinityLink 1.0.5

可以通过以下歌曲复现，其他曲名过短的歌也会出现:
[响 - 里里](https://music.163.com/song?id=2102062429)
[R - Roselia](https://music.163.com/song?id=1294899616)

播放后 easyrp 会报错，然后自动退出。
`Discord: error (4000: child "activity" fails because [child "state" fails because ["state" length must be at least 2 characters long]])`
目测 state (σôì) 长度确实大于2个字符，但是歌曲名 (响) 是1个字符

<img width="867" alt="Screenshot 2024-05-01 234751" src="https://github.com/BetterNCM/InfinityLink/assets/33804090/5b3ac85e-806a-4a1d-87c9-9ea2f8c2ea42">

**Comment by std-microblock** [comment]
应该是easyrp的问题？也有可能是dc api限制
