### ISSUE TITLE
Windows 显示显示不出歌名

### ISSUE THREAD

**Issue by ColderCof** [BetterNCM/InfinityLink#17]
![image](https://github.com/BetterNCM/InfinityLink/assets/129467165/586b403e-fa60-4293-8f78-a2d386941a0f)
播歌的时候只显示loading，有解答吗？

**Comment by MicroCBer** [comment]
你选中的信息获取方式失败了，请调整设置后切一首歌再试

**Comment by ColderCof** [comment]
不是很会用，能指导下吗，谢谢
