### ISSUE TITLE
无法构建，缺失未被上传的文件

### ISSUE THREAD

**Issue by cewno** [BetterNCM/InfinityLink#19]
`BetterNCMNativePlugin.h`文件未被上传，无法构建
![image](https://github.com/BetterNCM/InfinityLink/assets/121725066/28ba6f2a-a41c-4853-8d61-b7bf53885aef)

**Comment by cewno** [comment]
补充图：
![image](https://github.com/BetterNCM/InfinityLink/assets/121725066/b8d0ff31-c770-4422-9d31-cc1c00ebe225)
![image](https://github.com/BetterNCM/InfinityLink/assets/121725066/b1d6bbcd-cffc-41ea-9549-8e8e50ae5cb1)

**Comment by MicroCBer** [comment]
这个文件是bncm sdk在 BetterNCM 主仓库里 自己下下来找个地方放吧（
