### ISSUE TITLE
【suggestion】希望也可以同步播放进度

### ISSUE THREAD

**Issue by cow-your-sister** [BetterNCM/InfinityLink#2]
![image](https://user-images.githubusercontent.com/88882901/216308058-836f6102-abc9-4817-84cd-2ac2c1f7a615.png)
我用的是【ModernFlyouts】这款第三方软件实现的音量条，希望在MSTC中也链接上当前歌曲的播放进度，谢谢！

**Comment by MicroCBer** [comment]
我们之前试过，ms 貌似在 win11 已经放弃这个进度条了，设了也没用，所以没做

**Comment by cow-your-sister** [comment]
我用的是Win10😂

**Comment by cow-your-sister** [comment]
![image](https://user-images.githubusercontent.com/88882901/217433512-43d34515-ff7f-4cb3-98f8-77bed822d508.png)
隔壁spotify都支持😂
