### ISSUE TITLE
希望能修改SMTC不能传输时间轴的BUG

### ISSUE THREAD

**Issue by inventling** [BetterNCM/InfinityLink#23]
已标星，大佬你好，我目前在用Lyricify Lite， 通过SMTC获取歌曲信息和时间轴在桌面显示歌词。Spotify可以向SMTC发送时间轴信息，这样歌曲跳转进度时歌词也会跟随改变，但我用InfinityLink插件时歌词并不会在歌曲跳转进度时跟随改变。我通过在Lyricify Lite 交流群里得知，这是因为跟QQ音乐一样SMTC没有传时间轴的原因，希望大佬能修复一下，不胜感谢。此外，Lyricify 作者也希望大佬能够修复一下此BUG，这样也就双赢而且Lyricify Lite 的文档也会推荐这个插件。

**Comment by Silvigarabis** [comment]
似乎在2.10.12版本的网易云用这个插件，SMTC里还是没有时间轴。至少使用Lyricify Lite获取不到相关信息。

**Comment by inventling** [comment]
> 似乎在2.10.12版本的网易云用这个插件，SMTC里还是没有时间轴。至少使用Lyricify Lite获取不到相关信息。

[pull29有人修复了这个问题，但是好像没有更新](https://github.com/BetterNCM/InfinityLink/pull/29)

**Comment by Forest-Lee** [comment]
+1
