### ISSUE TITLE
使用一段时间后缓存会很大

### ISSUE THREAD

**Issue by JTFA** [BetterNCM/InfinityLink#6]
建议增加限制缓存大小功能

**Comment by Xionghaizi001** [comment]
+1，用久了缓存直接按GB算，硬盘扛不住

**Comment by cdwc233** [comment]
支持，就是C:\betterncm\InfLink-Thumbnail-Cache此文件夹，希望每次打开的时候自动清除上上次的缓存

**Comment by lgc2333** [comment]
![image](https://github.com/BetterNCM/InfinityLink/assets/59048777/1204995f-65a4-4385-bb82-34753aa37715)

蚌埠住了

**Comment by Minelu** [comment]
我也是，而且播放一次都会产生一个专辑图片的缓存
