### ISSUE TITLE
4月30日版本，更新之后网易云音乐无法启动。

### ISSUE THREAD

**Issue by Douzi-Qishen** [BetterNCM/InfinityLink#7]
4月30日版本，更新之后网易云音乐无法启动。删除插件后，正常启动。
 双击打开网易云音乐，无法看到软件启动的画面。无错误提示

**Comment by Douzi-Qishen** [comment]
> 

BetterNCM版本 1.0.3
适配BetterNCM版本 1.2.0
网易云版本 2.10.8

**Comment by jgckM** [comment]
克隆项目到本地，把项目回滚，自己在编译一个，就好了

**Comment by cdwc233** [comment]
去C:\betterncm\plugins里面删除InfLink打开再安装就行了
