### ISSUE TITLE
一些关于 Discord Rich Presence 的建议

### ISSUE THREAD

**Issue by lgc2333** [BetterNCM/InfinityLink#9]
- 自定义标题，信息展示，按钮等，最好可以提供变量
- 给一个选项可以控制显示音乐的 已播放时间 或 剩余时间
- 类型改成 `Listening`(`Listening to` / `正在听`) 而不是现在的 `Playing`（最好可以自定义）
- 未播放音乐时应为 `Idleing` 而不是维持原状态

**Comment by yangnuozhen** [comment]
有些东西好像是固定的.....

要改可以自己到[EasyRP仓库](https://github.com/Pizzabelly/EasyRP)看教程（

**Comment by yangnuozhen** [comment]
> 有些东西好像是固定的.....
> 
> 要改可以自己到[EasyRP仓库](https://github.com/Pizzabelly/EasyRP)看教程（

根据[EasyRP仓库](https://github.com/Pizzabelly/EasyRP)教程配置完成取得ClientID后，[修改该行](https://github.com/BetterNCM/InfinityLink/blob/9a8ba0b0a76b0b208a77967f1c0d5d263984e49d/src/Receivers/dc-rpc.ts#L19)成你刚刚取得的ClientID。

---

对于新人比较友好的修改方法：将Plugins文件夹中的`InfLink-*.*.*.plugin`解压到`Plugins_dev\InfLink-*.*.*\`并备份删除Plugins中的`InfLink-*.*.*.plugin`插件本体，然后使用[Visual Studio Code](https://code.visualstudio.com/)打开`Plugins_dev\InfLink-*.*.*\index.js`文件，按下`Ctrl + F`寻找文字`ClientID`，如图
![image](https://github.com/BetterNCM/InfinityLink/assets/56541171/d7f72db0-73df-4cab-a6b1-b7dbccb92cfd)

一样的，修改这里的ClientID即可。

---

如果你还是嫌自己配置Discord APP麻烦的话，可以直接把上面用到的ClientID替换成我已经配置好的。它显示起来就像这样：
![image](https://github.com/BetterNCM/InfinityLink/assets/56541171/3ca61a3e-f8ef-4ce9-9253-d4493ae3363c)
![image](https://github.com/BetterNCM/InfinityLink/assets/56541171/ad8b2291-4e98-4287-b53c-a6b862b379ba)

```
ClientID=1102520131566972970
```
